name: Unit Test

on:
  push:
    branches: [ master ]
  pull_request:
    branches: [ master ]

jobs:
  build:

    runs-on: ubuntu-latest

    strategy:
      matrix:
        java-version: [ 17 ]

    steps:
    - uses: actions/checkout@v2
    - uses: actions/setup-java@v2
      with:
        java-version: ${{ matrix.java-version }}
        distribution: adopt
    - name: Run unit tests and assemble APKs
      uses: gradle/gradle-build-action@v2
      with:
        arguments: assembleProdDebug testProdReleaseUnitTest
    - name: Check Output
      run: bash ./etc/CheckBuild/check-release.sh test
     
    - name: Upload APK as Artifact
      uses: actions/upload-artifact@v4  # 建议使用最新版本
      with:
        name: xdrip-app  # 产物名称，可自定义
        path: |
          app/build/outputs/apk/prod/release/*.apk
          app/build/outputs/apk/prod/debug/*.apk
